name: pokeflame
repository: https://github.com/TesteurManiak/pokeflame

packages:
  - packages/**
ignore:
  - "packages/**/example"
ide:
  intellij: false

scripts:
  analyze:
    run: melos exec -- "flutter analyze --no-fatal-infos"
    description: |
      Run `flutter analyze` in all packages.
        - Note: you can also rely on your IDEs Dart Analysis / Issues window.
  test:
    run: melos exec -- "flutter test"
    description: Run `flutter test` for a specific package.
    select-package:
      dir-exists: "test"

  coverage:
    run: melos exec -- "flutter test --coverage"
    description: Run `flutter test --coverage` for a specific package.
    select-package:
      dir-exists: "test"

command:
  bootstrap:
    usePubspecOverrides: true
